// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[id].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_500.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/logout.tsx";
import * as $6 from "./routes/unlock.tsx";
import * as $$0 from "./islands/chart.tsx";
import * as $$1 from "./islands/lock.tsx";
import * as $$2 from "./islands/table.tsx";

const manifest = {
  routes: {
    "./routes/[id].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_500.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/logout.tsx": $5,
    "./routes/unlock.tsx": $6,
  },
  islands: {
    "./islands/chart.tsx": $$0,
    "./islands/lock.tsx": $$1,
    "./islands/table.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
